export default {
  ROLE_BASED_ACCESS_POLICY: "RoleBasedAccessPolicy",
  ETHEREUM_FORK_ARBITER: "EthereumForkArbiter",
  NEUMARK: "Neumark",
  ICBM_LOCKED_ACCOUNT: "ICBMLockedAccount",
  ICBM_ETHER_TOKEN: "ICBMEtherToken",
  ICBM_EURO_TOKEN: "ICBMEuroToken",
  ICBM_COMMITMENT: "ICBMCommitment",
  UNIVERSE: "Universe",
  LOCKED_ACCOUNT: "LockedAccount",
  ETHER_TOKEN: "EtherToken",
  EURO_TOKEN: "EuroToken",
  EURO_TOKEN_CONTROLLER: "EuroTokenController",
  IDENTITY_REGISTRY: "IdentityRegistry",
  SIMPLE_EXCHANGE: "SimpleExchange",
};
